server:
  port: 9022

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/order
    username: root
    password: 1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace